### ISSUE TITLE
Monitoring/alarms for failures

### ISSUE THREAD

**Issue by cavis** [PRX/cms-audio-lambda#9]
To figure out how much of an issue #8 and PRX/publish.prx.org#451 are.

- [x] Alarm to slack on audio-lambda failures (ANY failure, including audio-not-found)

**Comment by cavis** [comment]
Waiting on #11, to have enough logging to create alarms.

**Comment by gcampo88** [comment]
what's the CMS #451 you're referring to here? CMS tix/PRs so far only go up to mid-300s!

**Comment by cavis** [comment]
Ah, right, should be publish.  Updated!

**Comment by pkarman** [comment]
blocked on #11

**Comment by cavis** [comment]
Any `[WARN]` or `[ERROR]` in the cloudwatch logs now trigger a slack tech-warning.  (Will need to go check the logs and see what went wrong).

Also updated the Fixer Dashboard in cloudwatch.
